# Generated by Django 5.0.1 on 2026-02-12 21:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('url', models.URLField(help_text='Base URL of the WordPress site')),
                ('wp_site_id', models.CharField(blank=True, help_text='WordPress site identifier', max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('sync_requested_at', models.DateTimeField(blank=True, help_text='When user requested a sync from dashboard', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business_type', models.CharField(blank=True, choices=[('local_service', 'Local/Service Business'), ('ecommerce', 'E-Commerce'), ('content_blog', 'Content/Blog'), ('saas', 'SaaS/Software'), ('other', 'Other')], help_text='Type of business', max_length=50, null=True)),
                ('primary_services', models.JSONField(blank=True, default=list, help_text='List of main services/products the business offers')),
                ('service_areas', models.JSONField(blank=True, default=list, help_text='List of geographic areas served (for local businesses)')),
                ('target_audience', models.TextField(blank=True, help_text='Description of target audience/customers')),
                ('business_description', models.TextField(blank=True, help_text='Brief description of the business')),
                ('onboarding_complete', models.BooleanField(default=False, help_text='Whether the business onboarding wizard has been completed')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sites', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'sites',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'url')},
            },
        ),
        migrations.CreateModel(
            name='APIKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Human-readable name for the API key', max_length=255)),
                ('key_hash', models.CharField(db_index=True, help_text='SHA-256 hash of the API key', max_length=64, unique=True)),
                ('key_prefix', models.CharField(help_text='First 16 characters of the key for display', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('usage_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_keys', to='sites.site')),
            ],
            options={
                'db_table': 'api_keys',
                'ordering': ['-created_at'],
            },
        ),
    ]
