# Generated by Django 5.0.1 on 2026-03-09 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0007_site_gsc_properties_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='gbp_place_id',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='site',
            name='gbp_reviews',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
