# Generated by Django 6.0.2 on 2026-02-13 21:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sites', '0005_site_gsc_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemPrompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt_key', models.CharField(max_length=50, unique=True)),
                ('prompt_text', models.TextField()),
                ('version', models.IntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'ai_system_prompts',
            },
        ),
        migrations.CreateModel(
            name='GeneratedPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conflict_id', models.IntegerField(help_text='ClusterResult ID that triggered this plan')),
                ('conflict_query', models.CharField(max_length=500)),
                ('action', models.CharField(max_length=50)),
                ('prompt_version', models.IntegerField()),
                ('context_payload', models.JSONField()),
                ('ai_response', models.JSONField()),
                ('provider', models.CharField(max_length=20)),
                ('model', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_plans', to='sites.site')),
            ],
            options={
                'db_table': 'ai_generated_plans',
                'ordering': ['-created_at'],
            },
        ),
    ]
