# Generated by Django 5.0.1 on 2026-02-12 21:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sites', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wp_post_id', models.IntegerField(help_text='WordPress post/page ID')),
                ('url', models.URLField()),
                ('title', models.CharField(max_length=500)),
                ('slug', models.SlugField(max_length=500)),
                ('content', models.TextField(blank=True)),
                ('excerpt', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('publish', 'Published'), ('draft', 'Draft'), ('private', 'Private')], default='publish', max_length=20)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('modified_at', models.DateTimeField(blank=True, null=True)),
                ('parent_id', models.IntegerField(blank=True, null=True)),
                ('menu_order', models.IntegerField(default=0)),
                ('yoast_title', models.CharField(blank=True, max_length=500)),
                ('yoast_description', models.TextField(blank=True)),
                ('featured_image', models.URLField(blank=True)),
                ('siloq_page_id', models.CharField(blank=True, max_length=255, null=True)),
                ('is_money_page', models.BooleanField(default=False, help_text='Is this a money/target page?')),
                ('is_homepage', models.BooleanField(default=False, help_text='Is this the homepage?')),
                ('is_noindex', models.BooleanField(default=False, help_text='Is this page set to noindex?')),
                ('last_synced_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent_silo', models.ForeignKey(blank=True, help_text='The money page this supporting page belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supporting_pages', to='seo.page')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='sites.site')),
            ],
            options={
                'db_table': 'pages',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LinkIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_type', models.CharField(choices=[('anchor_conflict', 'Anchor Text Conflict'), ('homepage_theft', 'Homepage Anchor Theft'), ('missing_target_link', 'Missing Link to Target'), ('missing_sibling_links', 'Missing Sibling Links'), ('orphan_page', 'Orphan Page'), ('cross_silo_link', 'Cross-Silo Link'), ('too_many_supporting', 'Too Many Supporting Pages')], max_length=50)),
                ('severity', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=20)),
                ('description', models.TextField()),
                ('recommendation', models.TextField(blank=True)),
                ('anchor_text', models.CharField(blank=True, max_length=500)),
                ('is_resolved', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='link_issues', to='sites.site')),
                ('page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='link_issues', to='seo.page')),
                ('related_pages', models.ManyToManyField(blank=True, related_name='related_link_issues', to='seo.page')),
            ],
            options={
                'db_table': 'link_issues',
                'ordering': ['-severity', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InternalLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_url', models.URLField(help_text='The URL being linked to')),
                ('anchor_text', models.CharField(blank=True, help_text='The clickable text of the link', max_length=500)),
                ('anchor_text_normalized', models.CharField(blank=True, help_text='Lowercase, stripped anchor text for comparison', max_length=500)),
                ('context_text', models.TextField(blank=True, help_text='Surrounding text for context (±50 chars)')),
                ('is_in_content', models.BooleanField(default=True, help_text='Is this link in main content (vs nav/footer)?')),
                ('is_nofollow', models.BooleanField(default=False, help_text='Does this link have rel=nofollow?')),
                ('is_valid', models.BooleanField(default=True, help_text='Is this a valid internal link?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='internal_links', to='sites.site')),
                ('source_page', models.ForeignKey(help_text='The page containing the link', on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_links', to='seo.page')),
                ('target_page', models.ForeignKey(blank=True, help_text='The page being linked to (null if external or not found)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='incoming_links', to='seo.page')),
            ],
            options={
                'db_table': 'internal_links',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AnchorTextConflict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anchor_text', models.CharField(help_text='The conflicting anchor text', max_length=500)),
                ('anchor_text_normalized', models.CharField(help_text='Lowercase normalized anchor', max_length=500)),
                ('occurrence_count', models.IntegerField(default=0, help_text='How many times this anchor appears across the site')),
                ('severity', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=20)),
                ('is_resolved', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anchor_conflicts', to='sites.site')),
                ('conflicting_pages', models.ManyToManyField(help_text='Pages this anchor text links to', related_name='anchor_conflicts', to='seo.page')),
            ],
            options={
                'db_table': 'anchor_text_conflicts',
                'ordering': ['-severity', '-occurrence_count'],
            },
        ),
        migrations.CreateModel(
            name='SEOData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_title', models.CharField(blank=True, max_length=500)),
                ('meta_description', models.TextField(blank=True)),
                ('meta_keywords', models.CharField(blank=True, max_length=500)),
                ('h1_count', models.IntegerField(default=0)),
                ('h1_text', models.CharField(blank=True, max_length=500)),
                ('h2_count', models.IntegerField(default=0)),
                ('h2_texts', models.JSONField(default=list, help_text='List of H2 headings')),
                ('h3_count', models.IntegerField(default=0)),
                ('h3_texts', models.JSONField(default=list, help_text='List of H3 headings')),
                ('internal_links_count', models.IntegerField(default=0)),
                ('external_links_count', models.IntegerField(default=0)),
                ('internal_links', models.JSONField(default=list, help_text='List of internal link URLs')),
                ('external_links', models.JSONField(default=list, help_text='List of external link URLs')),
                ('images_count', models.IntegerField(default=0)),
                ('images_without_alt', models.IntegerField(default=0)),
                ('images', models.JSONField(default=list, help_text='List of image URLs and alt texts')),
                ('word_count', models.IntegerField(default=0)),
                ('reading_time_minutes', models.FloatField(default=0)),
                ('seo_score', models.IntegerField(default=0, help_text='Overall SEO score (0-100)')),
                ('issues', models.JSONField(default=list, help_text="List of SEO issues found, e.g. [{'type': 'missing_meta_description', 'severity': 'high', 'message': '...'}]")),
                ('recommendations', models.JSONField(default=list, help_text='List of SEO recommendations')),
                ('has_canonical', models.BooleanField(default=False)),
                ('canonical_url', models.URLField(blank=True)),
                ('has_schema', models.BooleanField(default=False)),
                ('schema_type', models.CharField(blank=True, max_length=100)),
                ('scanned_at', models.DateTimeField(auto_now_add=True)),
                ('scan_version', models.CharField(default='1.0', max_length=50)),
                ('page', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='seo_data', to='seo.page')),
            ],
            options={
                'db_table': 'seo_data',
                'ordering': ['-scanned_at'],
            },
        ),
        migrations.AddIndex(
            model_name='page',
            index=models.Index(fields=['site', 'status'], name='pages_site_id_e97a01_idx'),
        ),
        migrations.AddIndex(
            model_name='page',
            index=models.Index(fields=['url'], name='pages_url_f5ef97_idx'),
        ),
        migrations.AddIndex(
            model_name='page',
            index=models.Index(fields=['is_money_page'], name='pages_is_mone_525ba2_idx'),
        ),
        migrations.AddIndex(
            model_name='page',
            index=models.Index(fields=['is_homepage'], name='pages_is_home_afbfd5_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='page',
            unique_together={('site', 'wp_post_id')},
        ),
        migrations.AddIndex(
            model_name='internallink',
            index=models.Index(fields=['site', 'source_page'], name='internal_li_site_id_e1c924_idx'),
        ),
        migrations.AddIndex(
            model_name='internallink',
            index=models.Index(fields=['site', 'target_page'], name='internal_li_site_id_7e2254_idx'),
        ),
        migrations.AddIndex(
            model_name='internallink',
            index=models.Index(fields=['anchor_text_normalized'], name='internal_li_anchor__14ddb9_idx'),
        ),
    ]
