# Generated by Django 5.0.1 on 2026-02-21 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seo', '0006_content_job'),
        ('seo', '0006_page_type_classification'),
        ('seo', '0018_siteentityprofile'),
    ]

    operations = [
    ]
