# Generated by Django 5.0.1 on 2026-03-09 21:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seo', '0025_merge_gsc_conflicts'),
        ('sites', '0008_site_intelligence'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SiloHealthScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(default=0)),
                ('details', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'silo_health_scores',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SiteIntelligence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_type', models.CharField(default='general', max_length=50)),
                ('primary_goal', models.TextField(blank=True)),
                ('raw_analysis', models.JSONField(default=dict)),
                ('hub_pages', models.JSONField(default=list)),
                ('spoke_pages', models.JSONField(default=list)),
                ('orphan_pages', models.JSONField(default=list)),
                ('architecture_problems', models.JSONField(default=list)),
                ('content_gaps', models.JSONField(default=list)),
                ('cannibalization_risks', models.JSONField(default=list)),
                ('generated_at', models.DateTimeField(auto_now=True)),
                ('generation_error', models.TextField(blank=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='cannibalizationconflict',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='conflictpage',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='conflictresolution',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='contentauditlog',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='contenthealthscore',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='freshnessalert',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='keywordassignment',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='keywordassignmenthistory',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='lifecyclequeue',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='pageanalysis',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='pagemetadata',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='redirectregistry',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='silodefinition',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='silokeyword',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='siteentityprofile',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='validationlog',
            options={'managed': False},
        ),
        migrations.RemoveIndex(
            model_name='slugchangelog',
            name='slug_change_site_idx',
        ),
        migrations.RemoveIndex(
            model_name='slugchangelog',
            name='slug_change_page_idx',
        ),
        migrations.RemoveIndex(
            model_name='slugchangelog',
            name='slug_change_site_page_idx',
        ),
        migrations.RemoveIndex(
            model_name='slugchangelog',
            name='slug_change_old_url_idx',
        ),
        migrations.RemoveIndex(
            model_name='slugchangelog',
            name='slug_change_new_url_idx',
        ),
        migrations.RemoveIndex(
            model_name='slugchangelog',
            name='slug_change_changed_at_idx',
        ),
        migrations.RenameIndex(
            model_name='conflict',
            new_name='conflicts_site_id_7a591e_idx',
            old_name='seo_confli_site_id_6f3a2b_idx',
        ),
        migrations.RenameIndex(
            model_name='conflict',
            new_name='conflicts_query_s_d87714_idx',
            old_name='seo_confli_query_s_7d4e1c_idx',
        ),
        migrations.RenameIndex(
            model_name='conflict',
            new_name='conflicts_severit_9bd34b_idx',
            old_name='seo_confli_severit_9a2f3d_idx',
        ),
        migrations.RenameIndex(
            model_name='contentjob',
            new_name='content_job_site_id_9845b1_idx',
            old_name='seo_conten_site_id_3e8b2a_idx',
        ),
        migrations.RenameIndex(
            model_name='contentjob',
            new_name='content_job_job_typ_8748c4_idx',
            old_name='seo_conten_job_typ_7c4f1d_idx',
        ),
        migrations.RenameIndex(
            model_name='contentjob',
            new_name='content_job_priorit_060323_idx',
            old_name='seo_conten_priorit_9a2e3f_idx',
        ),
        migrations.RenameIndex(
            model_name='contentjob',
            new_name='content_job_created_869db2_idx',
            old_name='seo_conten_create_8d5f4b_idx',
        ),
        migrations.RenameIndex(
            model_name='gscdata',
            new_name='gsc_data_page_id_d311f5_idx',
            old_name='seo_gscda_page_id_8c0f1a_idx',
        ),
        migrations.RenameIndex(
            model_name='gscdata',
            new_name='gsc_data_site_id_bb76e9_idx',
            old_name='seo_gscda_site_id_5c3f2a_idx',
        ),
        migrations.RenameIndex(
            model_name='gscdata',
            new_name='gsc_data_impress_f7d146_idx',
            old_name='seo_gscda_impress_2859f3_idx',
        ),
        migrations.RenameIndex(
            model_name='gscdata',
            new_name='gsc_data_positio_5e13be_idx',
            old_name='seo_gscda_positio_4e7b1c_idx',
        ),
        migrations.RenameIndex(
            model_name='internallink',
            new_name='internal_li_site_id_e1c924_idx',
            old_name='internal_links_site_source_idx',
        ),
        migrations.RenameIndex(
            model_name='internallink',
            new_name='internal_li_site_id_7e2254_idx',
            old_name='internal_links_site_target_idx',
        ),
        migrations.RenameIndex(
            model_name='internallink',
            new_name='internal_li_anchor__14ddb9_idx',
            old_name='internal_links_anchor_idx',
        ),
        migrations.RenameIndex(
            model_name='page',
            new_name='pages_is_mone_525ba2_idx',
            old_name='pages_is_mone_idx',
        ),
        migrations.RenameIndex(
            model_name='page',
            new_name='pages_is_home_afbfd5_idx',
            old_name='pages_is_home_idx',
        ),
        migrations.RemoveField(
            model_name='page',
            name='junk_action',
        ),
        migrations.RemoveField(
            model_name='page',
            name='junk_reason',
        ),
        migrations.RemoveField(
            model_name='page',
            name='parent_silo',
        ),
        migrations.AddField(
            model_name='clusterresult',
            name='conflict_subtype',
            field=models.CharField(default='active_conflict', help_text="'structural_warning' (0 GSC impressions) or 'active_conflict'", max_length=30),
        ),
        migrations.AddField(
            model_name='clusterresult',
            name='note',
            field=models.TextField(blank=True, help_text='Informational note for structural warnings'),
        ),
        migrations.AlterField(
            model_name='clusterresult',
            name='bucket',
            field=models.CharField(choices=[('SEARCH_CONFLICT', 'Search Conflict'), ('SITE_DUPLICATION', 'Site Duplication'), ('WRONG_WINNER', 'Wrong Winner'), ('BLOG_OVERLAP', 'Blog Overlap')], max_length=50),
        ),
        migrations.AlterField(
            model_name='conflict',
            name='winner_page',
            field=models.ForeignKey(blank=True, help_text='The page that should rank for this query', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='won_conflicts', to='seo.page'),
        ),
        migrations.AlterField(
            model_name='contentjob',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_content_jobs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='contentjob',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='page',
            name='page_builder',
            field=models.CharField(blank=True, choices=[('standard', 'Standard WordPress'), ('gutenberg', 'Gutenberg Block Editor'), ('elementor', 'Elementor'), ('cornerstone', 'Cornerstone / X Theme'), ('divi', 'Divi'), ('wpbakery', 'WPBakery'), ('beaver_builder', 'Beaver Builder'), ('unknown', 'Unknown')], default='unknown', help_text='Page builder detected during sync (elementor, cornerstone, divi, wpbakery, beaver_builder, gutenberg, standard)', max_length=30),
        ),
        migrations.AlterField(
            model_name='page',
            name='page_type_classification',
            field=models.CharField(choices=[('money', 'Money Page'), ('supporting', 'Supporting Content'), ('utility', 'Utility Page'), ('conversion', 'Conversion Page'), ('archive', 'Archive / Index'), ('product', 'E-commerce Product')], default='supporting', help_text='6-type page classification', max_length=20),
        ),
        migrations.AlterField(
            model_name='page',
            name='page_type_override',
            field=models.BooleanField(default=False, help_text='True if user manually set the page type (skip auto-reclassification)'),
        ),
        migrations.AlterField(
            model_name='pageclassification',
            name='word_count',
            field=models.IntegerField(default=0, help_text='Word count from SEOData (if available)'),
        ),
        migrations.AlterField(
            model_name='slugchangelog',
            name='changed_by',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='slugchangelog',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='slugchangelog',
            name='new_slug',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='slugchangelog',
            name='old_slug',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='slugchangelog',
            name='page_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='slugchangelog',
            name='reason',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='slugchangelog',
            name='redirect',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='seo.redirectregistry'),
        ),
        migrations.AlterField(
            model_name='slugchangelog',
            name='redirect_status',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='slugchangelog',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='slug_changes', to='sites.site'),
        ),
        migrations.AlterField(
            model_name='slugchangelog',
            name='slug_change_status',
            field=models.CharField(default='pending', max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='gscdata',
            unique_together={('page', 'site', 'query', 'date_start', 'date_end', 'device', 'country')},
        ),
        migrations.AddIndex(
            model_name='page',
            index=models.Index(fields=['page_type_classification'], name='pages_page_ty_490a32_idx'),
        ),
        migrations.AlterModelTable(
            name='slugchangelog',
            table=None,
        ),
        migrations.AddField(
            model_name='siteintelligence',
            name='site',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='intelligence', to='sites.site'),
        ),
    ]
